export enum ErrorCodes {
    NO_CONTEXT_PERMISSION = "FLUEXGL@AUDIO_ERROR_0001",
    NO_FILE_TYPE_FOUND = "FLUEXGL@AUDIO_ERROR_0002",
    PATH_TO_FILE_NOT_FOUND = "FLUEXGL@AUDIO_ERROR_0003",
    SAME_MASTER_CHANNEL = "FLUEXGL@AUDIO_ERROR_0004"
}

export enum WarningCodes {
    NO_DEFAULT_AUDIO_DEVICE_FOUND = "FLUEXGL@AUDIO_WARNING_0001"
}

export enum SuccessCodes {

}